version: "3.8"
services:
  blog:
    image: nginx:1.21.0
    container_name: blog-nginx
    restart: always
    volumes:
      - ./:/usr/share/nginx/html
      - ./templates:/etc/nginx/templates
      - /www/cert:/etc/nginx/cert
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=blog.towind.fun
      - NGINX_HOST_SSL_CRT=cert/1_blog.towind.fun_bundle.crt
      - NGINX_HOST_SSL_KEY=cert/2_blog.towind.fun.key
